<?php
/**
 * CardFunction
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.3.0.20210608.001
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FirstData\FirstApi\Client\Model;
use \FirstData\FirstApi\Client\ObjectSerializer;

/**
 * CardFunction Class Doc Comment
 *
 * @category Class
 * @description Card function. This field is required when performing transactions for Brazil merchants.
 * @package  FirstData\FirstApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CardFunction
{
    /**
     * Possible values of this enum
     */
    const CREDIT = 'CREDIT';
    const DEBIT = 'DEBIT';
    const PREPAID = 'PREPAID';
    const VOUCHER = 'VOUCHER';
    const UNDEFINED = 'UNDEFINED';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREDIT,
            self::DEBIT,
            self::PREPAID,
            self::VOUCHER,
            self::UNDEFINED,
        ];
    }
}


