<?php
/**
 * ResponseType
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.3.0.20210608.001
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FirstData\FirstApi\Client\Model;
use \FirstData\FirstApi\Client\ObjectSerializer;

/**
 * ResponseType Class Doc Comment
 *
 * @category Class
 * @description The type of the response.
 * @package  FirstData\FirstApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResponseType
{
    /**
     * Possible values of this enum
     */
    const BAD_REQUEST = 'BadRequest';
    const UNAUTHENTICATED = 'Unauthenticated';
    const UNAUTHORIZED = 'Unauthorized';
    const NOT_FOUND = 'NotFound';
    const GATEWAY_DECLINED = 'GatewayDeclined';
    const ENDPOINT_DECLINED = 'EndpointDeclined';
    const SERVER_ERROR = 'ServerError';
    const ENDPOINT_COMMUNICATION_ERROR = 'EndpointCommunicationError';
    const UNSUPPORTED_MEDIA_TYPE = 'UnsupportedMediaType';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BAD_REQUEST,
            self::UNAUTHENTICATED,
            self::UNAUTHORIZED,
            self::NOT_FOUND,
            self::GATEWAY_DECLINED,
            self::ENDPOINT_DECLINED,
            self::SERVER_ERROR,
            self::ENDPOINT_COMMUNICATION_ERROR,
            self::UNSUPPORTED_MEDIA_TYPE,
        ];
    }
}


