<?php
/**
 * ManagedRedirectTransactionType
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.4.0.20210824.002
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FirstData\FirstApi\Client\Model;
use \FirstData\FirstApi\Client\ObjectSerializer;

/**
 * ManagedRedirectTransactionType Class Doc Comment
 *
 * @category Class
 * @description Type of transaction to perform with ManagedRedirectRequest. Primary transaction types in requests include &#39;SALE&#39;, &#39;PREAUTH&#39;, &#39;PAYER_AUTH&#39;.
 * @package  FirstData\FirstApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ManagedRedirectTransactionType
{
    /**
     * Possible values of this enum
     */
    const SALE = 'SALE';
    const PREAUTH = 'PREAUTH';
    const PAYER_AUTH = 'PAYER_AUTH';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SALE,
            self::PREAUTH,
            self::PAYER_AUTH,
        ];
    }
}


